import { FeaturedItem } from "@/components/FeaturedItemCard";

export const mockProducts: Record<string, FeaturedItem[]> = {
  tech: [
    {
      id: 1001,
      item_name: "Wireless Earbuds Pro",
      price: 45000,
      old_price: 60000,
      image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
      store_name: "Tech Hub",
      category: "Tech",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 25,
      sme_id: 1,
    },
    {
      id: 1002,
      item_name: "USB-C Fast Charger",
      price: 15000,
      old_price: 22000,
      image_url: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop",
      store_name: "Power Solutions",
      category: "Tech",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 32,
      sme_id: 2,
    },
    {
      id: 1003,
      item_name: "Portable Power Bank",
      price: 35000,
      image_url: "https://images.unsplash.com/photo-1609941988998-3a0d0b1e8b16?w=400&h=400&fit=crop",
      store_name: "Mobile Accessories",
      category: "Tech",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: true,
      item_type: "product",
      sme_id: 3,
    },
    {
      id: 1004,
      item_name: "Wireless Gaming Mouse",
      price: 28000,
      old_price: 38000,
      image_url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=400&fit=crop",
      store_name: "Gaming Zone",
      category: "Tech",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: false,
      item_type: "product",
      discount_percent: 26,
      sme_id: 4,
    },
    {
      id: 1005,
      item_name: "Mechanical Keyboard RGB",
      price: 52000,
      old_price: 70000,
      image_url: "https://images.unsplash.com/photo-1587829191301-e8adb45ff91e?w=400&h=400&fit=crop",
      store_name: "Gaming Zone",
      category: "Tech",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: true,
      item_type: "product",
      discount_percent: 26,
      sme_id: 4,
    },
    {
      id: 1006,
      item_name: "HD Webcam 1080p",
      price: 22000,
      image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop",
      store_name: "Tech Hub",
      category: "Tech",
      is_featured: false,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 1,
    },
  ],
  fashion: [
    {
      id: 2001,
      item_name: "Designer Blazer",
      price: 85000,
      old_price: 120000,
      image_url: "https://images.unsplash.com/photo-1591047990979-e81a6f69cfe1?w=400&h=400&fit=crop",
      store_name: "Fashion Forward",
      category: "Fashion",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: true,
      item_type: "product",
      discount_percent: 29,
      sme_id: 5,
    },
    {
      id: 2002,
      item_name: "Premium Jeans",
      price: 45000,
      old_price: 65000,
      image_url: "https://images.unsplash.com/photo-1542272604-787c62d465d1?w=400&h=400&fit=crop",
      store_name: "Denim Co",
      category: "Fashion",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 31,
      sme_id: 6,
    },
    {
      id: 2003,
      item_name: "Leather Handbag",
      price: 75000,
      image_url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop",
      store_name: "Luxury Bags",
      category: "Fashion",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: true,
      item_type: "product",
      sme_id: 7,
    },
    {
      id: 2004,
      item_name: "Sneaker Collection",
      price: 55000,
      old_price: 78000,
      image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
      store_name: "Shoe Paradise",
      category: "Fashion",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 30,
      sme_id: 8,
    },
    {
      id: 2005,
      item_name: "Summer Dress",
      price: 38000,
      old_price: 52000,
      image_url: "https://images.unsplash.com/photo-1595777712802-4b01e64271e8?w=400&h=400&fit=crop",
      store_name: "Fashion Forward",
      category: "Fashion",
      is_featured: false,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 27,
      sme_id: 5,
    },
    {
      id: 2006,
      item_name: "Wool Coat",
      price: 95000,
      image_url: "https://images.unsplash.com/photo-1539533057440-7814baea1002?w=400&h=400&fit=crop",
      store_name: "Luxury Wear",
      category: "Fashion",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: true,
      item_type: "product",
      sme_id: 9,
    },
  ],
  food: [
    {
      id: 3001,
      item_name: "Organic Coffee Beans",
      price: 28000,
      old_price: 38000,
      image_url: "https://images.unsplash.com/photo-1514432324607-2e467f4af445?w=400&h=400&fit=crop",
      store_name: "Coffee House",
      category: "Food",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 26,
      sme_id: 10,
    },
    {
      id: 3002,
      item_name: "Fresh Pasta Set",
      price: 15000,
      image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop",
      store_name: "Gourmet Foods",
      category: "Food",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 11,
    },
    {
      id: 3003,
      item_name: "Artisan Bread",
      price: 8000,
      image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop",
      store_name: "Bakery Plus",
      category: "Food",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 12,
    },
    {
      id: 3004,
      item_name: "Premium Olive Oil",
      price: 35000,
      old_price: 48000,
      image_url: "https://images.unsplash.com/photo-1606674902464-45a73aa60299?w=400&h=400&fit=crop",
      store_name: "Mediterranean Delights",
      category: "Food",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: true,
      item_type: "product",
      discount_percent: 27,
      sme_id: 13,
    },
    {
      id: 3005,
      item_name: "Organic Honey",
      price: 22000,
      image_url: "https://images.unsplash.com/photo-1578039351612-1e4ca16dc2d3?w=400&h=400&fit=crop",
      store_name: "Nature's Best",
      category: "Food",
      is_featured: false,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 14,
    },
    {
      id: 3006,
      item_name: "Spice Collection",
      price: 18000,
      image_url: "https://images.unsplash.com/photo-1596040306279-0e1b4f9e1fb8?w=400&h=400&fit=crop",
      store_name: "Spice Market",
      category: "Food",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 15,
    },
  ],
  beauty: [
    {
      id: 4001,
      item_name: "Facial Serum",
      price: 25000,
      old_price: 35000,
      image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop",
      store_name: "Beauty Essentials",
      category: "Beauty",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 29,
      sme_id: 16,
    },
    {
      id: 4002,
      item_name: "Moisturizing Cream",
      price: 32000,
      image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop",
      store_name: "Skin Care Plus",
      category: "Beauty",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 17,
    },
    {
      id: 4003,
      item_name: "Lipstick Collection",
      price: 18000,
      old_price: 25000,
      image_url: "https://images.unsplash.com/photo-1596462502278-af407713e489?w=400&h=400&fit=crop",
      store_name: "Makeup Studio",
      category: "Beauty",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 28,
      sme_id: 18,
    },
    {
      id: 4004,
      item_name: "Hair Treatment Oil",
      price: 16000,
      image_url: "https://images.unsplash.com/photo-1585647346739-fc0ee433096d?w=400&h=400&fit=crop",
      store_name: "Hair Care Pro",
      category: "Beauty",
      is_featured: false,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      sme_id: 19,
    },
    {
      id: 4005,
      item_name: "Face Mask Sheet",
      price: 12000,
      old_price: 16000,
      image_url: "https://images.unsplash.com/photo-1557223556-51c7a052b585?w=400&h=400&fit=crop",
      store_name: "Beauty Essentials",
      category: "Beauty",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "product",
      discount_percent: 25,
      sme_id: 16,
    },
    {
      id: 4006,
      item_name: "Sunscreen SPF50",
      price: 22000,
      image_url: "https://images.unsplash.com/photo-1600314675502-90bbd608b697?w=400&h=400&fit=crop",
      store_name: "Sun Protection",
      category: "Beauty",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: true,
      item_type: "product",
      sme_id: 20,
    },
  ],
  entertainment: [
    {
      id: 5001,
      item_name: "Concert Tickets Pack",
      price: 150000,
      old_price: 200000,
      image_url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
      store_name: "Event Hub",
      category: "Entertainment",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: false,
      item_type: "service",
      discount_percent: 25,
      sme_id: 21,
    },
    {
      id: 5002,
      item_name: "Movie Night Package",
      price: 35000,
      image_url: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=400&h=400&fit=crop",
      store_name: "Entertainment Plus",
      category: "Entertainment",
      is_featured: true,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "service",
      sme_id: 22,
    },
    {
      id: 5003,
      item_name: "DJ Service",
      price: 450000,
      old_price: 600000,
      image_url: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=400&h=400&fit=crop",
      store_name: "Music Events",
      category: "Entertainment",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: false,
      item_type: "service",
      discount_percent: 25,
      sme_id: 23,
    },
    {
      id: 5004,
      item_name: "Photography Session",
      price: 280000,
      image_url: "https://images.unsplash.com/photo-1502634534042-35c99e27a49e?w=400&h=400&fit=crop",
      store_name: "Photo Studio",
      category: "Entertainment",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: false,
      item_type: "service",
      sme_id: 24,
    },
    {
      id: 5005,
      item_name: "Gaming Console Rental",
      price: 25000,
      old_price: 35000,
      image_url: "https://images.unsplash.com/photo-1535275335684-0fa217cd3101?w=400&h=400&fit=crop",
      store_name: "Game Lounge",
      category: "Entertainment",
      is_featured: false,
      in_stock: true,
      fast_delivery: true,
      free_shipping: false,
      item_type: "service",
      discount_percent: 29,
      sme_id: 25,
    },
    {
      id: 5006,
      item_name: "Event Planning Service",
      price: 500000,
      image_url: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=400&h=400&fit=crop",
      store_name: "Event Planners",
      category: "Entertainment",
      is_featured: true,
      in_stock: true,
      fast_delivery: false,
      free_shipping: false,
      item_type: "service",
      sme_id: 26,
    },
  ],
};
