// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnaajzmbkisybwnjeiie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYWFqem1ia2lzeWJ3bmplaWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjY0NTIsImV4cCI6MjA5MDA0MjQ1Mn0.4YL8sotyk8noKqUMMcciWSwcIRG4_oy-J4a-B1KJA2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url: string, options?: RequestInit) => {
      try {
        // Use 15 second timeout for Supabase queries (more generous than 10s)
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 15000);

        try {
          const response = await fetch(url, {
            ...options,
            signal: controller.signal,
          });
          clearTimeout(timeoutId);
          return response;
        } catch (fetchError: any) {
          clearTimeout(timeoutId);
          throw fetchError;
        }
      } catch (error: any) {
        // Log detailed error info for debugging
        const errorInfo = {
          url,
          message: error?.message,
          name: error?.name,
          code: error?.code,
          timestamp: new Date().toISOString(),
        };

        // Only log timeouts and auth errors, not every error
        if (error?.name === "AbortError" || error?.message?.includes("timeout")) {
          console.warn("[Supabase] Request timeout:", errorInfo);
        } else if (error?.status === 401 || error?.status === 403) {
          console.warn("[Supabase] Auth error:", errorInfo);
        }

        throw error;
      }
    },
  },
});

/**
 * Setup error handling for auth failures.
 * This runs once on app initialization.
 */
export const setupAuthErrorHandling = () => {
  // Listen for auth state changes and handle errors
  const { data: { subscription } } = supabase.auth.onAuthStateChange(async (event, session) => {
    if (event === "SIGNED_OUT" && session === null) {
      // Session was cleared - this is expected
      console.debug("[Auth] Session cleared");
    }

    if (event === "TOKEN_REFRESHED") {
      console.debug("[Auth] Token refreshed successfully");
    }

    // Handle lock/concurrency errors gracefully
    if (event === "SIGNED_IN" || event === "TOKEN_REFRESHED") {
      // Wait a moment after auth state changes to avoid lock conflicts
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  });

  return subscription;
};

/**
 * Clear stale or invalid tokens from localStorage.
 * Useful for fixing "Refresh Token Not Found" errors.
 */
export const clearInvalidTokens = async () => {
  try {
    // Check if we have a valid session
    const { data: { session } } = await supabase.auth.getSession();

    if (!session) {
      // No valid session - clear all auth tokens
      localStorage.removeItem(`sb-${SUPABASE_URL.split('//')[1].split('.')[0]}-auth-token`);

      // Also clear generic keys
      Object.keys(localStorage).forEach((key) => {
        if (key.includes('supabase') || key.includes('auth-token')) {
          localStorage.removeItem(key);
        }
      });

      console.warn("[Auth] Cleared invalid tokens");
    }
  } catch (error) {
    console.error("[Auth] Error clearing tokens:", error);
  }
};

/**
 * Force sign out and clear all session data.
 * Used when refresh token is truly invalid.
 */
export const forceSignOut = async () => {
  try {
    await supabase.auth.signOut({ scope: "local" });
  } catch (error) {
    console.warn("[Auth] Error during signout:", error);
  }

  // Always clear tokens regardless of signout result
  try {
    Object.keys(localStorage).forEach((key) => {
      if (key.includes('supabase') || key.includes('auth') || key.includes('sb-')) {
        localStorage.removeItem(key);
      }
    });
  } catch (error) {
    console.warn("[Auth] Error clearing localStorage:", error);
  }
};
